### ISSUE TITLE
'/' in Query

### ISSUE THREAD

**Issue by bruskowski** [marckrenn/framer-QueryInterface#2]
Hi!
I ran into some errors once in a while using this module in the framer cloud environment, apparently caused by one or more slashes in the query URL:
e.g. framer.cloud/xyz?/key=value
or framer.cloud/xyz?key1=value1/&key2=value2

I am no expert on queries but apparently they were resolved by removing the slash in "/&" in line 46:
`separator = if url.indexOf("?") isnt -1 then "&" else "?"`

Maybe this is useful for others as well.

Great plugin, useful in so many ways, thank you!

**Comment by marckrenn** [comment]
Thanks for tracking this one down!

Do you want to open a PR? Would like to have you as an _official_ contributor.

> I am no expert on queries

 
I'm no expert neither 😉

> Great plugin, useful in so many ways, thank you!

You're very welcome 😀 Really glad someone else sees some value in this module – I personally use it in almost all of my (commercial) projects!

**Comment by bruskowski** [comment]
Sure, will do that right away! 👍
